### ISSUE TITLE
Keep getting error while creating category

### ISSUE THREAD

**Issue by heeryung** [Ejhfast/empath-client#3] opened 2017-09-29 05:00 UTC
I keep getting an error everytime I try to create a category.
Python commands I used are as `follows:

```
from empath import Empath
lexicon = Empath()
lexicon.create_category("cold_war", ["cold_war"], model="nytimes")
```

The error I got is as follows:

requests.exceptions.ConnectionError: HTTPConnectionPool(host='54.148.189.209', port=8000): Max retries exceeded with url: /create_category (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x102fed1d0>: Failed to establish a new connection: [Errno 61] Connection refused',))

Thanks!

**Comment by t-zubyak** [comment] 2017-10-02 20:32
@Ejhfast I've also encountered the same issue as @heeryung. Based on the code, creating a category seems to be hitting an external server.
I was just curious if the server needs to be set up separately to be able to create categories, or is 54.148.189.209 a public hosted Empath backend solution?

I've also noticed that creating a category doesn't work on http://empath.stanford.edu, which is referenced in your paper on Empath (great work, btw)!

Any help would be greatly appreciated.

Thanks in advance!

**Comment by tonychuo** [comment] 2017-10-03 09:52
Got the same problem here.  It failed to ... HTTPConnectionPool(host='54.148.189.209', port=8000) .
Any advise would be greatly appreciated.
Thanks in advance.

**Comment by Ejhfast** [comment] 2017-10-03 16:03
Should be fixed now!

**Comment by t-zubyak** [comment] 2017-10-03 16:05
@Ejhfast just confirmed that it is working.
Thanks a lot!

**Comment by tonychuo** [comment] 2017-10-03 16:31
Yes.  It is working now.
Thanks a lot.

Tony Chuo 😸

**Closed as completed** 2017-10-10 18:37 UTC

**Comment by huda-esmail** [comment] 2022-05-28 11:05
Hi, I am having the same problem now. Problem in creating a new category. This is the error i got.

requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='54.148.189.209', port=8000): Max retries exceeded with url: /create_category (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x131887070>, 'Connection to 54.148.189.209 timed out. (connect timeout=None)'))

Thank you!
